sudo: required
services:
  - docker

before_install:
  - docker build -t henrymcbean/react-test -f ./client/Dockerfile.dev ./client

script:
  # -- -- coverage - Removed from command below, Not working, used -e CI=true
  - docker run -e CI=true henrymcbean/react-test npm test 

after_success:
  - docker build -t henrymcbean/multi-client ./client
  - docker build -t henrymcbean/multi-nginx ./nginx
  - docker build -t henrymcbean/multi-server ./server
  - docker build -t henrymcbean/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push henrymcbean/multi-client
  - docker push henrymcbean/multi-nginx
  - docker push henrymcbean/multi-server
  - docker push henrymcbean/multi-worker
