version: '3'
services:
  postgres:
    image: 'postgres:10.5'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  api:  # Change from server, could cause conflict in nginx/default.conf
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports: 
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    # ports:
    #  - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    tty: true
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379